# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 01:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.CharField(max_length=50)),
                ('creator_email', models.EmailField(max_length=254)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('x', models.CharField(max_length=500)),
                ('y', models.CharField(max_length=500)),
                ('solution', models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('image_url', models.URLField()),
            ],
        ),
    ]
