# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creategame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.SlugField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
